server:
  port: 8513

spring:
  application:
    name: service-cart
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.6.100:8848
    sentinel:
      transport:
        dashboard: 192.168.6.100:8080
  data:
    redis:
      host: 192.168.6.100
      port: 6379
      password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    #time-zone: GMT+8